"""initial schema

Revision ID: 0313279216b4
Revises: 
Create Date: 2026-05-30 13:32:15.092979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0313279216b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicle_catalog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('epa_vehicle_id', sa.String(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('drive', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cylinders', sa.Integer(), nullable=True),
    sa.Column('displacement', sa.Float(), nullable=True),
    sa.Column('vehicle_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('atv_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fuel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_mpg', sa.Float(), nullable=True),
    sa.Column('highway_mpg', sa.Float(), nullable=True),
    sa.Column('combined_mpg', sa.Float(), nullable=True),
    sa.Column('fuel_type_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city_mpg_alt', sa.Float(), nullable=True),
    sa.Column('highway_mpg_alt', sa.Float(), nullable=True),
    sa.Column('combined_mpg_alt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_catalog_epa_vehicle_id'), 'vehicle_catalog', ['epa_vehicle_id'], unique=True)
    op.create_table('user_vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mpg_override', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['vehicle_catalog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('start_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('gallons_used', sa.Float(), nullable=False),
    sa.Column('fuel_price', sa.Float(), nullable=False),
    sa.Column('trip_cost', sa.Float(), nullable=False),
    sa.Column('co2_kg', sa.Float(), nullable=False),
    sa.Column('trip_date', sa.DateTime(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['user_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('user_vehicles')
    op.drop_index(op.f('ix_vehicle_catalog_epa_vehicle_id'), table_name='vehicle_catalog')
    op.drop_table('vehicle_catalog')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
