"""initial schema

Revision ID: 10ceb2c14622
Revises: 
Create Date: 2026-05-28 18:21:36.512604

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ceb2c14622'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('start_lat', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trips', sa.Column('end_lat', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trips', sa.Column('start_lng', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trips', sa.Column('end_lng', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trips', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.alter_column('trips', 'distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('vehicle_catalog', 'city_mpg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('vehicle_catalog', 'highway_mpg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('vehicle_catalog', 'combined_mpg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_vehicle_catalog_epa_vehicle_id'), 'vehicle_catalog', ['epa_vehicle_id'], unique=True)
    op.drop_column('vehicle_catalog', 'nhtsa_vehicle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_catalog', sa.Column('nhtsa_vehicle_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vehicle_catalog_epa_vehicle_id'), table_name='vehicle_catalog')
    op.alter_column('vehicle_catalog', 'combined_mpg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('vehicle_catalog', 'highway_mpg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('vehicle_catalog', 'city_mpg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trips', 'distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('trips', 'end_time')
    op.drop_column('trips', 'start_time')
    op.drop_column('trips', 'end_lng')
    op.drop_column('trips', 'start_lng')
    op.drop_column('trips', 'end_lat')
    op.drop_column('trips', 'start_lat')
    # ### end Alembic commands ###
