"""make catalog_id nullable on user_vehicles

Revision ID: 132a54623d85
Revises: 9ba9e1ecd8e9
Create Date: 2026-07-18 17:43:46.908975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132a54623d85'
down_revision: Union[str, Sequence[str], None] = '9ba9e1ecd8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_vehicles', 'catalog_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_vehicles', 'catalog_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
