"""add route image key to trips

Revision ID: 9ba9e1ecd8e9
Revises: 4d3b4daa38e1
Create Date: 2026-07-09 12:53:59.619827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ba9e1ecd8e9'
down_revision: Union[str, Sequence[str], None] = '4d3b4daa38e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('route_image_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'route_image_key')
    # ### end Alembic commands ###
