"""add gps coordinates to trips

Revision ID: b28fe77d597e
Revises: 0313279216b4
Create Date: 2026-06-02 19:58:23.023027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28fe77d597e'
down_revision: Union[str, Sequence[str], None] = '0313279216b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'start_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trips', 'end_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trips', 'start_lat',
                existing_type=sa.VARCHAR(),
                type_=sa.Float(),
                postgresql_using='start_lat::double precision',
                nullable=True)

    op.alter_column('trips', 'start_lng',
                existing_type=sa.VARCHAR(),
                type_=sa.Float(),
                postgresql_using='start_lng::double precision',
                nullable=True)

    op.alter_column('trips', 'end_lat',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        postgresql_using='end_lat::double precision',
        nullable=True)

    op.alter_column('trips', 'end_lng',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        postgresql_using='end_lng::double precision',
        nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'end_lng',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('trips', 'start_lng',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('trips', 'end_lat',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('trips', 'start_lat',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('trips', 'end_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trips', 'start_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
